### ISSUE TITLE
Add service OpenAITTSService

### ISSUE THREAD

**Issue by janwout** [pipecat-ai/pipecat#196]
The OpenAI Text-To-Speech sounds very natural in different languages. Is this something pipecat wants to support?

**Comment by TomTom101** [comment]
In fact, you might want to try [this forked branch](https://github.com/TomTom101/pipecat/tree/TomTom101/openai_tts) with a OpenAI TTS service added

**Comment by TomTom101** [comment]
Make sure to set the correct sample rate in the daily params, OpenAI returns 24kHz audio:
```python
transport = DailyTransport(
            room_url,
            None,
            "Say One Thing From an LLM",
            DailyParams(
                audio_out_enabled=True,
                audio_out_sample_rate=24_000,
            ),
        )
```

**Comment by janwout** [comment]
I tried implementing the service from the pr: I get a 404 error, did not find out yet why:

```
openai.NotFoundError: Error code: 404 - {'error': {'message': 'Invalid URL (POST /v1/audio/speech)', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by janwout** [comment]
full stacktrace

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jwee/projects/alfabert/src/bot.py", line 210, in <module>
    asyncio.run(main(config.u, config.t))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jwee/projects/alfabert/src/bot.py", line 182, in main
    await runner.run(intro_task)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/pipeline/runner.py", line 32, in run
    await task.run()
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/pipeline/task.py", line 69, in run
    await asyncio.gather(self._process_up_task, self._process_down_task)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/pipeline/task.py", line 92, in _process_down_queue
    await self._source.process_frame(frame, FrameDirection.DOWNSTREAM)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/pipeline/task.py", line 35, in process_frame
    await self.push_frame(frame, direction)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/processors/frame_processor.py", line 51, in push_frame
    await self._next.process_frame(frame, direction)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/pipeline/pipeline.py", line 65, in process_frame
    await self._source.process_frame(frame, FrameDirection.DOWNSTREAM)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/pipeline/pipeline.py", line 26, in process_frame
    await self.push_frame(frame, direction)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/processors/frame_processor.py", line 51, in push_frame
    await self._next.process_frame(frame, direction)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/services/openai.py", line 215, in process_frame
    await self._process_context(context)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/services/openai.py", line 141, in _process_context
    await self.push_frame(TextFrame(chunk.choices[0].delta.content))
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/processors/frame_processor.py", line 51, in push_frame
    await self._next.process_frame(frame, direction)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/services/ai_services.py", line 110, in process_frame
    await self._process_text_frame(frame)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/services/ai_services.py", line 98, in _process_text_frame
    await self._push_tts_frames(text)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/services/ai_services.py", line 102, in _push_tts_frames
    await self.process_generator(self.run_tts(text))
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/services/ai_services.py", line 34, in process_generator
    async for f in generator:
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/services/openai.py", line 295, in run_tts
    async with self._client.audio.speech.with_streaming_response.create(
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/openai/_response.py", line 634, in __aenter__
    self.__response = await self._api_request
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/openai/resources/audio/speech.py", line 159, in create
    return await self._post(
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/openai/_base_client.py", line 1790, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/openai/_base_client.py", line 1493, in request
    return await self._request(
  File "/home/jwee/envs/alfabert/lib/python3.10/site-packages/openai/_base_client.py", line 1584, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'Invalid URL (POST /v1/audio/speech)', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by TomTom101** [comment]
It uses the official `openai` package. Please check if your installed version is up to date and you don't have any unknown envs set, that possibly override the `OPENAI_BASE_URL`. This service does not specify urls or paths at all.

**Comment by janwout** [comment]
I tried with openai 1.26.0 and openai 1.30.5. No environment variables set. 

pip freeze ->

```
aiohttp==3.9.5
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.3.0
arrow==1.3.0
async-timeout==4.0.3
attrs==23.2.0
azure-cognitiveservices-speech==1.37.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
daily-python==0.9.1
distro==1.9.0
dnspython==2.6.1
email_validator==2.1.1
exceptiongroup==1.2.1
fal_client==0.4.0
fastapi==0.111.0
fastapi-cli==0.0.4
filelock==3.14.0
frozenlist==1.4.1
future==1.0.0
grpcio==1.64.0
h11==0.14.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
httpx-sse==0.4.0
idna==3.7
Jinja2==3.1.4
loguru==0.7.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
multidict==6.0.5
numpy==1.26.4
openai==1.30.5
orjson==3.10.3
pillow==10.3.0
Pint==0.23
pipecat-ai==0.0.25
protobuf==4.25.3
pydantic==2.7.1
pydantic_core==2.18.2
Pygments==2.18.0
pyht==0.0.28
pyloudnorm==0.1.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
PyYAML==6.0.1
requests==2.32.2
rich==13.7.1
scipy==1.13.1
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
starlette==0.37.2
tqdm==4.66.4
typer==0.12.3
types-python-dateutil==2.9.0.20240316
typing_extensions==4.11.0
ujson==5.10.0
urllib3==2.2.1
uvicorn==0.29.0
uvloop==0.19.0
watchfiles==0.21.0
websockets==12.0
yarl==1.9.4
```

**Comment by janwout** [comment]
I called the service with  `model="gpt-4o"`, user error, cloding ticket

**Comment by janwout** [comment]
I called the service with model="gpt-4o", user error, closing ticket

**Comment by TomTom101** [comment]
Gpt-4o should work fine however, I ran my tests with this model

**Comment by bhaktatejas922** [comment]
is the voice super low for you guys? voice is super low and slow. wondering if the assumption is the audio is 44khz (eleven labs) so its being stretched? 

eleven labs tts works fine

**Comment by bhaktatejas922** [comment]
I think the TwilioFrameSerializer serialize and deserialize assume 16000 instead of 24000. Having it take in frequency as an input/output respectively should fix it
