### ISSUE TITLE
Storytelling Chatbot example fails with JavaScript error

### ISSUE THREAD

**Issue by dominikroblek** [pipecat-ai/pipecat#398]
If I attempt to run examples/storytelling-chatbot following the instructions in the README.md file, I get the following JavaScript console error:

69-095760e877e82c4b.js:1 TypeError: Cannot read properties of undefined (reading 'ondevicechange')
    at nx (d50e61c5-729bf43d5cce1859.js:19:31033)
    at Z.startListeningForDeviceChanges (d50e61c5-729bf43d5cce1859.js:19:42326)
    at new Z (d50e61c5-729bf43d5cce1859.js:19:49895)
    at Function.value (d50e61c5-729bf43d5cce1859.js:19:118289)
    at 647-07448eb149f02d56.js:1:32531
    at aI (fd9d1056-15205bcf7b0e6812.js:1:72882)
    at a3 (fd9d1056-15205bcf7b0e6812.js:1:84323)
    at a5 (fd9d1056-15205bcf7b0e6812.js:1:84961)
    at a8 (fd9d1056-15205bcf7b0e6812.js:1:84845)
    at a5 (fd9d1056-15205bcf7b0e6812.js:1:84941)

**Comment by dominikroblek** [comment]
It works fine, if I access it by http://localhost:7860/ instead of by http://0.0.0.0:7860/
