### ISSUE TITLE
ImportError: cannot import name 'CallClient' from 'daily'

### ISSUE THREAD

**Issue by imaxwel** [pipecat-ai/pipecat#404]
I'm having trouble running the examples. I keep getting errors. Anyone able to lend a hand?

(venv) (base) root@instance-20240603-wangfq:~/Downloads/pipecat/examples/foundational# python 01-say-one-thing.py                                                                                                                   [81/241]
Traceback (most recent call last):
  File "/root/Downloads/pipecat/examples/foundational/01-say-one-thing.py", line 17, in <module>
    from pipecat.transports.services.daily import DailyParams, DailyTransport
  File "/root/Downloads/pipecat/venv/lib/python3.12/site-packages/pipecat/transports/services/daily.py", line 15, in <module>
    from daily import (
ModuleNotFoundError: No module named 'daily'
(venv) (base) root@instance-20240603-wangfq:~/Downloads/pipecat/examples/foundational# pip install daily
Collecting daily
  Downloading daily-0.2.1-py3-none-any.whl.metadata (3.1 kB)
Collecting slackclient==2.2.1 (from daily)
  Downloading slackclient-2.2.1-py2.py3-none-any.whl.metadata (11 kB)
Collecting arrow==0.15.2 (from daily)
  Downloading arrow-0.15.2-py2.py3-none-any.whl.metadata (6.1 kB)
Collecting Click==7.0 (from daily)
  Downloading Click-7.0-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting halo==0.0.28 (from daily)
  Downloading halo-0.0.28-py3-none-any.whl.metadata (6.6 kB)
Collecting gspread==3.1.0 (from daily)
  Downloading gspread-3.1.0-py3-none-any.whl.metadata (1.2 kB)
Collecting python-dateutil==2.8.0 (from daily)
  Downloading python_dateutil-2.8.0-py2.py3-none-any.whl.metadata (7.6 kB)
Collecting google-api-python-client==1.7.11 (from daily)
  Downloading google-api-python-client-1.7.11.tar.gz (142 kB)                                                                                                                                                                                 Installing build dependencies ... done
  Getting requirements to build wheel ... done                                                                                                                                                                                                Preparing metadata (pyproject.toml) ... done                                                                                                                                                                                              Collecting google-auth-httplib2==0.0.3 (from daily)
  Downloading google_auth_httplib2-0.0.3-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting google-auth-oauthlib==0.4.1 (from daily)
  Downloading google_auth_oauthlib-0.4.1-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client==1.7.11->daily)
  Downloading httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)
Collecting google-auth>=1.4.1 (from google-api-python-client==1.7.11->daily)
  Downloading google_auth-2.34.0-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting six<2dev,>=1.6.1 (from google-api-python-client==1.7.11->daily)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client==1.7.11->daily)
  Downloading uritemplate-3.0.1-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib==0.4.1->daily)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting requests>=2.2.1 (from gspread==3.1.0->daily)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting log-symbols>=0.0.13 (from halo==0.0.28->daily)
  Downloading log_symbols-0.0.14-py3-none-any.whl.metadata (523 bytes)
Collecting spinners>=0.0.23 (from halo==0.0.28->daily)
  Downloading spinners-0.0.24-py3-none-any.whl.metadata (576 bytes)
Collecting cursor>=1.2.0 (from halo==0.0.28->daily)
  Downloading cursor-1.3.5.tar.gz (15 kB)
  Installing build dependencies ... done                                                                                                                                                                                            [32/241]
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting termcolor>=1.1.0 (from halo==0.0.28->daily)
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
Collecting colorama>=0.3.9 (from halo==0.0.28->daily)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: aiohttp>3.5.2 in /root/Downloads/pipecat/venv/lib/python3.12/site-packages (from slackclient==2.2.1->daily) (3.9.5)
Requirement already satisfied: aiosignal>=1.1.2 in /root/Downloads/pipecat/venv/lib/python3.12/site-packages (from aiohttp>3.5.2->slackclient==2.2.1->daily) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /root/Downloads/pipecat/venv/lib/python3.12/site-packages (from aiohttp>3.5.2->slackclient==2.2.1->daily) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /root/Downloads/pipecat/venv/lib/python3.12/site-packages (from aiohttp>3.5.2->slackclient==2.2.1->daily) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /root/Downloads/pipecat/venv/lib/python3.12/site-packages (from aiohttp>3.5.2->slackclient==2.2.1->daily) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /root/Downloads/pipecat/venv/lib/python3.12/site-packages (from aiohttp>3.5.2->slackclient==2.2.1->daily) (1.9.4)
Collecting cachetools<6.0,>=2.0.0 (from google-auth>=1.4.1->google-api-python-client==1.7.11->daily)
  Downloading cachetools-5.5.0-py3-none-any.whl.metadata (5.3 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.4.1->google-api-python-client==1.7.11->daily)
  Downloading pyasn1_modules-0.4.0-py3-none-any.whl.metadata (3.4 kB)
Collecting rsa<5,>=3.1.4 (from google-auth>=1.4.1->google-api-python-client==1.7.11->daily)
  Downloading rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Collecting pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 (from httplib2<1dev,>=0.9.2->google-api-python-client==1.7.11->daily)
  Downloading pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.2.1->gspread==3.1.0->daily)
  Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Requirement already satisfied: idna<4,>=2.5 in /root/Downloads/pipecat/venv/lib/python3.12/site-packages (from requests>=2.2.1->gspread==3.1.0->daily) (3.7)
Collecting urllib3<3,>=1.21.1 (from requests>=2.2.1->gspread==3.1.0->daily)
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests>=2.2.1->gspread==3.1.0->daily)
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib==0.4.1->daily)
  Downloading oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Collecting pyasn1<0.7.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->google-api-python-client==1.7.11->daily)
  Downloading pyasn1-0.6.0-py2.py3-none-any.whl.metadata (8.3 kB)
Downloading daily-0.2.1-py3-none-any.whl (8.3 kB)
Downloading arrow-0.15.2-py2.py3-none-any.whl (40 kB)
Downloading Click-7.0-py2.py3-none-any.whl (81 kB)
Downloading google_auth_httplib2-0.0.3-py2.py3-none-any.whl (6.3 kB)
Downloading google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)
Downloading gspread-3.1.0-py3-none-any.whl (16 kB)
Downloading halo-0.0.28-py3-none-any.whl (10 kB)
Downloading python_dateutil-2.8.0-py2.py3-none-any.whl (226 kB)
Downloading slackclient-2.2.1-py2.py3-none-any.whl (53 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading google_auth-2.34.0-py2.py3-none-any.whl (200 kB)
Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
Downloading log_symbols-0.0.14-py3-none-any.whl (3.1 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Downloading spinners-0.0.24-py3-none-any.whl (5.5 kB)
Using cached termcolor-2.4.0-py3-none-any.whl (7.7 kB)
Downloading uritemplate-3.0.1-py2.py3-none-any.whl (15 kB)
Downloading cachetools-5.5.0-py3-none-any.whl (9.5 kB)
Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
Downloading pyasn1_modules-0.4.0-py3-none-any.whl (181 kB)
Downloading pyparsing-3.1.2-py3-none-any.whl (103 kB)
Downloading rsa-4.9-py3-none-any.whl (34 kB)
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Downloading pyasn1-0.6.0-py2.py3-none-any.whl (85 kB)
Building wheels for collected packages: google-api-python-client, cursor
  Building wheel for google-api-python-client (pyproject.toml) ... done
  Created wheel for google-api-python-client: filename=google_api_python_client-1.7.11-py3-none-any.whl size=56518 sha256=dbee4c656f7f6fa20db12f9cac8a2120cecac7bc5c0a4b726d047c62d09fc532
  Stored in directory: /root/.cache/pip/wheels/7c/f0/e7/823ff15c8e0e2773881e016a69e902910c1d34dcce2b9dea7d
  Building wheel for cursor (pyproject.toml) ... done
  Created wheel for cursor: filename=cursor-1.3.5-py3-none-any.whl size=15820 sha256=fa2f37e05aec4b7a7ec513d2e4a0e6ae7ec7b6a8aac8de894b5773b11d6c79e1
  Stored in directory: /root/.cache/pip/wheels/c3/f6/8f/b582d4924b4d2d16d2a92ea825d225136fe5a284d99581e598
Successfully built google-api-python-client cursor
Installing collected packages: spinners, cursor, urllib3, uritemplate, termcolor, six, pyparsing, pyasn1, oauthlib, colorama, Click, charset-normalizer, certifi, cachetools, rsa, requests, python-dateutil, pyasn1-modules, log-symbols, h
ttplib2, slackclient, requests-oauthlib, halo, gspread, google-auth, arrow, google-auth-oauthlib, google-auth-httplib2, google-api-python-client, daily
Successfully installed Click-7.0 arrow-0.15.2 cachetools-5.5.0 certifi-2024.7.4 charset-normalizer-3.3.2 colorama-0.4.6 cursor-1.3.5 daily-0.2.1 google-api-python-client-1.7.11 google-auth-2.34.0 google-auth-httplib2-0.0.3 google-auth-o
authlib-0.4.1 gspread-3.1.0 halo-0.0.28 httplib2-0.22.0 log-symbols-0.0.14 oauthlib-3.2.2 pyasn1-0.6.0 pyasn1-modules-0.4.0 pyparsing-3.1.2 python-dateutil-2.8.0 requests-2.32.3 requests-oauthlib-2.0.0 rsa-4.9 six-1.16.0 slackclient-2.2
.1 spinners-0.0.24 termcolor-2.4.0 uritemplate-3.0.1 urllib3-2.2.2
(venv) (base) root@instance-20240603-wangfq:~/Downloads/pipecat/examples/foundational# python 01-say-one-thing.py
Traceback (most recent call last):
  File "/root/Downloads/pipecat/examples/foundational/01-say-one-thing.py", line 17, in <module>
    from pipecat.transports.services.daily import DailyParams, DailyTransport
  File "/root/Downloads/pipecat/venv/lib/python3.12/site-packages/pipecat/transports/services/daily.py", line 15, in <module>
    from daily import (
ImportError: cannot import name 'CallClient' from 'daily' (/root/Downloads/pipecat/venv/lib/python3.12/site-packages/daily.py)
(venv) (base) root@instance-20240603-wangfq:~/Downloads/pipecat/examples/foundational#

**Comment by imaxwel** [comment]
I got it - I installed the wrong 'daily' dependency. That's why the examples aren't working.
(venv) (base) root@instance-20240603-wangfq:~/Downloads/pipecat# pip uninstall daily
Found existing installation: daily 0.2.1
Uninstalling daily-0.2.1:
  Would remove:
    /root/Downloads/pipecat/venv/bin/daily
    /root/Downloads/pipecat/venv/daily/client_sheets.json
    /root/Downloads/pipecat/venv/daily/template.txt
    /root/Downloads/pipecat/venv/lib/python3.12/site-packages/daily-0.2.1.dist-info/*
    /root/Downloads/pipecat/venv/lib/python3.12/site-packages/daily.py
Proceed (Y/n)? Y
  Successfully uninstalled daily-0.2.1
(venv) (base) root@instance-20240603-wangfq:~/Downloads/pipecat# pip install daily-python
Collecting daily-python
  Using cached daily_python-0.10.1-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Using cached daily_python-0.10.1-cp37-abi3-manylinux_2_28_x86_64.whl (13.7 MB)
Installing collected packages: daily-python
Successfully installed daily-python-0.10.1
