### ISSUE TITLE
CartesiaTTSService: Potential Bug in WebSocket Handling

### ISSUE THREAD

**Issue by dominikroblek** [pipecat-ai/pipecat#471]
Occasionally, I encounter this error in CartesiaTTSService. Could this be a bug in the CartesiaTTSService, the Cartesia library, or my code?

2024-09-18 09:25:01.202 | ERROR    | pipecat.services.cartesia:_receive_task_handler:189 - CartesiaTTSService#0 exception: no close frame received or sent
Traceback (most recent call last):

  File "/Users/magnacarta/p/sunray/.venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
                    │    └ <function WebSocketCommonProtocol.read_message at 0x13c9f4360>
                    └ <websockets.legacy.client.WebSocketClientProtocol object at 0x175ec6fc0>
  File "/Users/magnacarta/p/sunray/.venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
                  │    │                        │    └ 1048576
                  │    │                        └ <websockets.legacy.client.WebSocketClientProtocol object at 0x175ec6fc0>
                  │    └ <function WebSocketCommonProtocol.read_data_frame at 0x13c9f4400>
                  └ <websockets.legacy.client.WebSocketClientProtocol object at 0x175ec6fc0>
  File "/Users/magnacarta/p/sunray/.venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
                  │    │          └ 1048576
                  │    └ <function WebSocketCommonProtocol.read_frame at 0x13c9f44a0>
                  └ <websockets.legacy.client.WebSocketClientProtocol object at 0x175ec6fc0>
  File "/Users/magnacarta/p/sunray/.venv/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
                  │     └ <classmethod(<function Frame.read at 0x13c9cefc0>)>
                  └ <class 'websockets.legacy.framing.Frame'>
  File "/Users/magnacarta/p/sunray/.venv/lib/python3.12/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
                 └ <bound method StreamReader.readexactly of <StreamReader eof limit=32768 transport=<asyncio.sslproto._SSLProtocolTransport obj...

  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/streams.py", line 750, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
          │          │                   │           └ 2
          │          │                   └ b''
          │          └ <class 'asyncio.exceptions.IncompleteReadError'>
          └ <module 'asyncio.exceptions' from '/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/pyth...

asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

**Comment by sourav-bz** [comment]
getting the same issue as well, i think the connection is timing out after inactivity and not connecting back after that.

**Comment by Shoshin23** [comment]
I'm getting a similar issue, but with ElevenLabs TTS. Here's the link to my issue: https://github.com/pipecat-ai/pipecat/issues/563

This seems to be happening fairly commonly. I'm not sure if this is to do with my code or if it's to do with Pipecat. My code itself is fairly straightforward. It uses based on one of the foundational examples so i'm not sure. 

Thanks!

**Comment by markbackman** [comment]
Hi, I'm interested in understanding this issue. Do you have repro steps that you can share?

**Comment by markbackman** [comment]
@aconchillo made changes to improve the reconnection logic of the Cartesia websocket: https://github.com/pipecat-ai/pipecat/pull/796. That should close this issue. If you still see this problem, please open a new issue.

**Comment by nikcaryo-super** [comment]
still seeing this behavior on 0.52. 


<img width="1217" alt="Screenshot 2025-01-08 at 6 23 15 PM" src="https://github.com/user-attachments/assets/0e36cf74-c59b-47b4-a254-7fa72b714a48" />

**Comment by markbackman** [comment]
@nikcaryo-super can you share repro information for that case? I know we're connected in Slack, but if you don't mind sharing here, that would be really helpful.

Last night, I ran the [twilio-chatbot example](https://github.com/pipecat-ai/pipecat/tree/main/examples/twilio-chatbot), as it's more similar to your setup (e.g. `FastAPIWebsocketTransport` for a phone use case), but I wasn't able to repro the issue. When the user hangs up, everything gracefully disconnects. Logs following the user hanging up the phone call are:

```
INFO:     connection closed
2025-01-07 20:40:31.739 | DEBUG    | pipecat.services.deepgram:_disconnect:208 - Disconnecting from Deepgram
tasks cancelled error: 
tasks cancelled error: 
2025-01-07 20:40:32.243 | DEBUG    | pipecat.services.cartesia:_disconnect_websocket:215 - Disconnecting from Cartesia
2025-01-07 20:40:34.196 | DEBUG    | pipecat.pipeline.runner:run:31 - Runner PipelineRunner#0 finished running PipelineTask#0
```

Getting a repro case and steps for this would be very helpful.

Ideally, that repro case would be distilled to something simpler than just your entire application. For example, do you hit this issue running the twilio-chatbot example? If not, how is your code different from the twilio-chatbot example? More information along those lines would help us understand how to approach this problem.

**Comment by nikcaryo-super** [comment]
I'll see if I can tomorrow. Notably, what i'm seeing with this is well before a hangup. It's in the middle of the call at some point where cartesia disconnects. Since this error is being raised at all, I suspect we're hitting the "connection retry" limit for the websocket.

I'd expect that every time we successfully connect to cartesia, the "attempt counter" resets. If we ever hit the limit - it should be a fatal error and the pipeline should exit and we should be able to handle that and hangup the call or something. Instead, what I think we're seeing now, is that when that error is raised it never actually does anything and our bot just stops responding.

**Comment by markbackman** [comment]
@nikcaryo-super great tip! Cartesia is unique in that if there are 5 minutes of inactivity, it will attempt to disconnect the websocket. Using this, I was able to confirm that the retry counter is _not_ getting reset after a successful connection. This can lead to false positive disconnects.

This change should better handle reconnects: https://github.com/pipecat-ai/pipecat/pull/962.

**Comment by markbackman** [comment]
Closing this, as #962 has been closed.
